name: build vault
 
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:
 
permissions:
  contents: write
  pages: write
  id-token: write
 
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.TOKEN}}

      - name: Checkout obsidian vault
        uses: actions/checkout@v5
        with:
            repository: rohanjnr/obsidian-backup
            token: ${{ secrets.TOKEN }}
            path: obsidian-backup
      
      - name: run LS
        run: ls -l

      - name: Create content folder
        run: ./create_content.sh
      
      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci

      - name: Build Quartz
        run: npx quartz build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: public

 
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4